# Generated by Django 5.0.3 on 2024-07-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
