# Generated by Django 5.0.3 on 2024-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_end_time',
            field=models.TimeField(default=None),
        ),
    ]
