# Generated by Django 5.0.3 on 2024-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_appointment_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_end_time',
            field=models.TimeField(),
        ),
    ]
