# Generated by Django 5.0.3 on 2024-08-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_end_date',
            field=models.DateField(default=None),
        ),
    ]
