# Generated by Django 5.0.3 on 2024-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_appointment_appointment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Not Seen', 'Not Seen'), ('Seen', 'Seen'), ('Approved', 'Approved'), ('Waiting', 'Waiting'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
